name: Continuous Delivery
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  #   _________                __  .__
  # \_   ___ \  ____   _____/  |_|__| ____  __ __  ____  __ __  ______
  # /    \  \/ /  _ \ /    \   __\  |/    \|  |  \/  _ \|  |  \/  ___/
  # \     \___(  <_> )   |  \  | |  |   |  \  |  (  <_> )  |  /\___ \
  #  \______  /\____/|___|  /__| |__|___|  /____/ \____/|____//____  >
  #         \/            \/             \/                        \/
  # .___        __                              __  .__
  # |   | _____/  |_  ____   ________________ _/  |_|__| ____   ____
  # |   |/    \   __\/ __ \ / ___\_  __ \__  \\   __\  |/  _ \ /    \
  # |   |   |  \  | \  ___// /_/  >  | \// __ \|  | |  (  <_> )   |  \
  # |___|___|  /__|  \___  >___  /|__|  (____  /__| |__|\____/|___|  /
  #          \/          \/_____/            \/                    \/
  build:
    runs-on: ubuntu-latest
    needs: [security-audit]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build

  # lint:
  #   runs-on: ubuntu-latest
  #   needs: [security-audit]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Install Dependencies
  #       run: npm i
  #     - name: Lint the code
  #       run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [security-audit]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Run Unit Tests
        run: npm t

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check for security issue
        run: npm audit --audit-level=critical

  static-analysis:
    runs-on: ubuntu-latest
    needs: [security-audit]
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - name: Perform Analysis
        uses: github/codeql-action/analyze@v1
  # _________                __  .__
  # \_   ___ \  ____   _____/  |_|__| ____  __ __  ____  __ __  ______
  # /    \  \/ /  _ \ /    \   __\  |/    \|  |  \/  _ \|  |  \/  ___/
  # \     \___(  <_> )   |  \  | |  |   |  \  |  (  <_> )  |  /\___ \
  #  \______  /\____/|___|  /__| |__|___|  /____/ \____/|____//____  >
  #         \/            \/             \/                        \/
  # ________                .__                                      __
  # \______ \   ____ ______ |  |   ____ ___.__. _____   ____   _____/  |_
  #  |    |  \_/ __ \\____ \|  |  /  _ <   |  |/     \_/ __ \ /    \   __\
  #  |    `   \  ___/|  |_> >  |_(  <_> )___  |  Y Y  \  ___/|   |  \  |
  # /_______  /\___  >   __/|____/\____// ____|__|_|  /\___  >___|  /__|
  #         \/     \/|__|               \/          \/     \/     \/
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - run: npm i && npm run build
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

  smoke-test:
    runs-on: ubuntu-latest
    needs: [deploy-prod]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Perform smoke test
        run: export TEST_URL=https://codex.academy && npm i && npm run smoke
