name: Continuous Delivery
on:
  push:
    branches:
      - master
  pull_request:

jobs:

#   ______   ______   .__   __. .___________. __  .__   __.  __    __    ______    __    __       _______.     
#  /      | /  __  \  |  \ |  | |           ||  | |  \ |  | |  |  |  |  /  __  \  |  |  |  |     /       |     
# |  ,----'|  |  |  | |   \|  | `---|  |----`|  | |   \|  | |  |  |  | |  |  |  | |  |  |  |    |   (----`     
# |  |     |  |  |  | |  . `  |     |  |     |  | |  . `  | |  |  |  | |  |  |  | |  |  |  |     \   \         
# |  `----.|  `--'  | |  |\   |     |  |     |  | |  |\   | |  `--'  | |  `--'  | |  `--'  | .----)   |        
#  \______| \______/  |__| \__|     |__|     |__| |__| \__|  \______/   \______/   \______/  |_______/         
                                                                                                             
#  __  .__   __. .___________. _______   _______ .______          ___   .___________. __    ______   .__   __. 
# |  | |  \ |  | |           ||   ____| /  _____||   _  \        /   \  |           ||  |  /  __  \  |  \ |  | 
# |  | |   \|  | `---|  |----`|  |__   |  |  __  |  |_)  |      /  ^  \ `---|  |----`|  | |  |  |  | |   \|  | 
# |  | |  . `  |     |  |     |   __|  |  | |_ | |      /      /  /_\  \    |  |     |  | |  |  |  | |  . `  | 
# |  | |  |\   |     |  |     |  |____ |  |__| | |  |\  \----./  _____  \   |  |     |  | |  `--'  | |  |\   | 
# |__| |__| \__|     |__|     |_______| \______| | _| `._____/__/     \__\  |__|     |__|  \______/  |__| \__| 
                                                                                                             
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

